version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: deptno/circleci-awscli-node8:0.1
    working_directory: ~/repo

    steps:
      - checkout
      - run: mkdir -p ~/.aws
      - run: echo -e "[default]\naws_access_key_id=$AWS_ACCESS_KEY_ID\naws_secret_access_key=$AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
      - run: echo -e "[default]\noutput = json\nregion = ap-northeast-2\n" > ~/.aws/config
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
      - run: npm install
      - run: npm run build
      - run: npm run export
      - run: npm run deploy
      - run: npm run invalidation
      - save_cache:
          key: v1-npm-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
